name: Self hosted runner test

on:
  workflow_dispatch:
    inputs:
      test:
        description: Do you want to run?
        required: true
        default: 'yes'
        
 jobs:
   some-job:
     steps:
       - name: Test
         runs-on: self-hosted
         run: |
           echo "Hello, $JAVA_HOME"
   
