name: Self hosted runner test

on:
  workflow_dispatch:
    inputs:
      test:
        description: Do you want to run?
        required: true
        default: 'yes'
        
jobs:
 some-job:
   runs-on: self-hosted
   steps:
     - name: Test
       run: |
         echo "Hello, MAVNE HOME: $MVN_HOME, HELLO HOME: $HELLO_HOME Terraform Home: $TERRAFORM_HOME"
         printenv
   
